### ISSUE TITLE
readNetFromONNX throws exception

### ISSUE THREAD

**Issue by leandro-svg** [UNeedCryDear/yolov5-seg-opencv-dnn-cpp#2]
Deat @UNeedCryDear ,
Thank you for your work.

I have a quite an annoying exception while reading my ONNX file :
`yolov5s-seg.onnx
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.1.1) /home/nvidia/debbuild/opencv-4.1.1/opencv/modules/dnn/src/onnx/onnx_importer.cpp:110: error: (-215:Assertion failed) !tensor_proto.raw_data().empty() || !tensor_proto.float_data().empty() || !tensor_proto.double_data().empty() || !tensor_proto.int64_data().empty() in function 'getMatFromTensor'`

This exception comes when i'm calling : _**net = readNetFromONNX(netPath);**_

Do you have any idea where this error comes from? I am using opencv-4.1.1 .
FYI, I have used your command line to export the model without the --dnn argument, since they removed it.

Thank you

**Comment by UNeedCryDear** [comment]
Make sure your opencv>=4.5.0

**Comment by leandro-svg** [comment]
It worked with 4.5.2. Thank you !
